export const USER_SUBMIT = 'USER_SUBMIT';
export const USER_SUBMIT_REQUEST = 'USER_SUBMIT_REQUEST';
export const USER_SUBMIT_FAILURE = 'USER_SUBMIT_FAILURE';

export const MESSAGE_SUBMIT = 'MESSAGE_SUBMIT';
export const MESSAGE_SUBMIT_REQUEST = 'MESSAGE_SUBMIT_REQUEST';
export const MESSAGE_SUBMIT_FAILURE = 'MESSAGE_SUBMIT_FAILURE';
